# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# 	 http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

"""Integration tests for the Network Firewall API.
"""

import pytest
import time

from acktest.resources import random_suffix_name
from acktest.k8s import resource as k8s
from e2e import service_marker, load_networkfirewall_resource, create_firewall_resource, delete_firewall_resource
from e2e.replacement_values import REPLACEMENT_VALUES
from e2e.bootstrap_resources import get_bootstrap_resources
from e2e.tests.helper import NetworkFirewallValidator, create_simple_firewall_policy

UPDATE_WAIT_AFTER_SECONDS = 30
# It takes really long for firewall to be created/deleted.
TIMEOUT_SECONDS = 1200

@pytest.fixture
def simple_firewall(request):
    fw_resource_name = random_suffix_name("firewall-ack-test", 24)
    resources = get_bootstrap_resources()

    policy_ref, policy_cr = create_simple_firewall_policy()
    policy_status = policy_cr["status"]
    policy_resp = policy_status["firewallPolicyResponse"]
    policy_arn = policy_resp["firewallPolicyARN"]
    subnet_id = resources.SharedTestVPC.public_subnets.subnet_ids[0]

    replacements = REPLACEMENT_VALUES.copy()
    replacements["FIREWALL_NAME"] = fw_resource_name
    replacements["VPC_ID"] = resources.SharedTestVPC.vpc_id
    replacements["SUBNET_ID"] = subnet_id
    replacements["LOG_DESTINATION_TYPE"] = "S3"
    replacements["LOG_DESTINATION"] = resources.LogsBucket.name
    replacements["TRAFFIC_TYPE"] = "ALL"
    replacements["FIREWALL_POLICY_ARN"] = policy_arn

    ref, cr = create_firewall_resource(
        "firewalls",
        fw_resource_name,
        "firewall",
        replacements,
    )

    assert cr["status"]["firewall"]["firewallPolicyARN"] == policy_arn

    # Create a new firewall policy
    new_policy_ref, policy_cr = create_simple_firewall_policy()
    policy_status = policy_cr["status"]
    policy_resp = policy_status["firewallPolicyResponse"]
    policy_arn = policy_resp["firewallPolicyARN"]

    # Update existing firewall with new policy
    updates = {
        "spec": {
            "firewallPolicyARN": policy_arn,
        }
    }
    k8s.patch_custom_resource(ref, updates)
    time.sleep(UPDATE_WAIT_AFTER_SECONDS)

    cr = k8s.get_resource(ref)

    # Ensure policy ARN was updated in the firewall
    assert cr is not None
    assert cr["status"]["firewall"]["firewallPolicyARN"] == policy_arn

    yield (ref, cr)

    # Try to delete, if doesn't already exist
    delete_firewall_resource(policy_ref)
    delete_firewall_resource(new_policy_ref)
    delete_firewall_resource(ref)

def create_adopted_resource_firewall(firewall_name):
    adopted_resource_name = random_suffix_name("firewall-ack-test-adopted-resource", 48)
    adopted_resource_fw_name = random_suffix_name("firewall-ack-test-adopted-resource-fw", 48)

    replacements = REPLACEMENT_VALUES.copy()
    replacements["ADOPTED_FIREWALL_NAME"] = adopted_resource_fw_name
    replacements["ADOPTED_RESOURCE_NAME"] = adopted_resource_name
    replacements["FIREWALL_NAME"] = firewall_name

    ref, cr = create_firewall_resource(
        "AdoptedResources",
        adopted_resource_name,
        "adopted_resource_firewall",
        replacements,
        "services.k8s.aws"
    )

    # Get Firewall CR generated by AdoptedResource
    fw_ref = k8s.CustomResourceReference(
        "networkfirewall.services.k8s.aws",
        "v1alpha1",
        "firewalls",
        adopted_resource_fw_name,
        namespace="default",
    )

    fw_cr = k8s.wait_resource_consumed_by_controller(fw_ref)

    # Try to delete, if doesn't already exist
    delete_firewall_resource(ref)

    return (fw_ref, fw_cr)


@service_marker
@pytest.mark.canary
class TestNetworkFirewall:
    def test_create_delete_using_adopted_resource(self, networkfirewall_client, simple_firewall):
        (fw, cr) = simple_firewall

        firewall_config = cr["status"]["firewall"]
        firewall_name = firewall_config["firewallName"]

        networkfirewall_validator = NetworkFirewallValidator(networkfirewall_client)
        # Check Network Firewall comes to READY state
        networkfirewall_validator.wait_for_firewall_creation_or_die(firewall_name, "READY", TIMEOUT_SECONDS)

        # Adopt firewall using AdoptedResource CR
        (fw_ref, fw_cr) = create_adopted_resource_firewall(firewall_name)

        # Delete k8s resource
        k8s.delete_custom_resource(fw_ref)

        # Check Firewall no longer exists in AWS
        networkfirewall_validator.wait_for_firewall_deletion_or_die(firewall_name, TIMEOUT_SECONDS)
